<center> <h1> GANs &#119070; &nbsp;Reels </h1>

</center>

## Code Demo ##

This notebook showcases our entire process of creating music using a Neural Network. At a high level, there are three main parts to our process of using a GAN to generate music. Namely:
1. Encoding: 
    Converting our dataset of Irish music to a form suitable for the GAN.
2. Training: 
    Feeding the curated data to our customized GAN, and decoding the results.
3. Decoding: 
    Converting the results from our GAN to music 

### 1. Encoding ###

This process can be broken down to 4 stages:
1. Sourcing: Getting the dataset from TheSessions.org/
2. Filtering: Pruning data that isn't in our relevant structure 
3. Cleaning: Using a structured notation to simplify ABC notation
4. Vectorizing: Creating vectors out of the cleaned data


In [ ]:
# Entire Encoding Process
from src.Generation import raw_to_npy as raw_data
raw_data.raw_abc_to_npy_file(update=False)

Folder "../Data" already exists. Skipping creation...
Folder "../Data/Clean/" already exists. Skipping creation...
Folder "../Data/Statistics/" already exists. Skipping creation...
Folder "../Data/Vectors/" already exists. Skipping creation...
Starting abc cleaning...
10675/31093 tunes successfully cleaned!




Finished cleaning abc strings.
Starting vectorization process.
Creating dataframe...
Size of Initial Frame: 10675
Size of Cleaned Frame: 6142

 - - - - - - - Table Data - - - - - - - 

0    [[64, 64, 64, 64, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2...
1    [[71, 71, 71, 71, 68, 68, 71, 71, 71, 71, 71, ...
2    [[66, 66, 64, 64, -5, -5, -5, -5, -5, -5, -5, ...
3    [[83, 83, 81, 81, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2...
4    [[62, 62, 62, 62, 62, 62, 57, 57, 59, 59, 57, ...
Name: notes, dtype: object
 
Random Tune Sample 
Tune
[64 64 64 64  2  2  2  2  2  2  2  2  2  2  2  2]
[66 66 73 73 73 73 71 71 73 73 73 73 66 66 73 73]
[73 73 73 73 71 71 73 73 76 76 73 73 71 71 69 69]
[68 68 64 64 71 71 64 6

finished entire process


### 2. Training ###

Our next step is to feed this curated data to our neural network. We opted for a Deconvolutional GAN since they are renowned for performing well on images, and making training a lot more stable. The parameters used were:
- Stride: 2
- Output function: Sigmoid
- Padding: 4 x 4 x 16
- Batch Size: 60

At a high level, this process consists of:
1. Building a Generator and a Discriminator
2. Padding and transposing data to suit our GAN
3. Checking for mode collapse every fixed number of iterations
4. Converting output of the GAN to a Vectorized array

In [ ]:
# Entire GAN Training Process
# from src.Model.MusicGAN import GAN
import numpy as np
data = np.load("../Data/Vectors/Common_Time_Notes.npy")
paddedData = np.pad(data, [[16,16]], mode='wrap') #pad bottom of image once, and pad left and right with 4 notes
# gan = GAN(paddedData, data)
# gan.train(100)

### 3. Decoding ###

After the training is done, we decode the resulting vector (provided the GAN didn't collapse) back to music, using essentially the inverse of our encoding process.

This consists of:
1. Converting Vectors to ABC Notation
2. Converting ABC Notation to a format readable by a Music Player

In [ ]:
# Decoding Process
# import matplotlib as plt
from src.Generation.Vectorizing import Decoding
num = 6

decoder = Decoding.Decoder(presentation=True)
generated = Decoding.decode_single_vector('generated_samples.npy', num, presentation=True)
decoder.play(generated[num] + 'z32')